#pragma once

#define TABLEINIT_OK 0
#define TABLEINIT_INVALID_CORNERS 1
#define TABLEINIT_INVALID_HOLES 2

#define BALLSINIT_OK 0
#define BALLSINIT_INVALID_WHITE 1
#define BALLSINIT_INVALID_CENTER 2
#define BALLSINIT_INVALID_DISTENCE 3
